export const options = [
  { value: '', label: 'Clear' },
  { value: 'Action', label: 'Action' },
  { value: 'Adventure', label: 'Adventure' },
  { value: 'Comedy', label: 'Comedy' },
  { value: 'Fantasy', label: 'Fantasy' },
  { value: 'Historical', label: 'Historical' },
  { value: 'Horror', label: 'Horror' },
  { value: 'Magic', label: 'Magic' },
  { value: 'Martial Arts', label: 'Martial Arts' },
  { value: 'Mecha', label: 'Mecha' },
  { value: 'Military', label: 'Military' },
  { value: 'Mystery', label: 'Mystery' },
  { value: 'Parody', label: 'Parody' },
  { value: 'Police', label: 'Police' },
  { value: 'Psychological', label: 'Psychological' },
  { value: 'Romance', label: 'Romance' },
  { value: 'Samurai', label: 'Samurai' },
  { value: 'School', label: 'School' },
  { value: 'Sci-Fi', label: 'Sci-Fi' },
  { value: 'Slice of Life', label: 'Slice of Life' },
  { value: 'Space', label: 'Space' },
  { value: 'Sports', label: 'Sports' },
  { value: 'Thriller', label: 'Thriller' },

]
